print("TRIGONOMETRIC CALCULATOR")
print("1) Calculate sine of an angle")
print("2) Calculate cosine of an angle")
print("3) Calculate tangent of an angle")
print("4) Exit.")
choice = input("Choose an option (1-4): ")